spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loja_virtual?autoReconnect=true
    username: postgres
    password: 75128359
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 200
      maximum-pool-size: 550
      idle-timeout: 10000
      pool-name: PoolHikari
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
      temp:
        '[use-jdbc-metadata-defaults]': true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          '[batch_size]': 4
          '[order_inserts]': true
          '[order_updates]': true

  server:
    servlet:
      context-path: /loja_virtual
    compression:
      enabled: true
      mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
      min-response-size: 1024
    http2:
      enabled: true
    tomcat:
      max-connections: 50000
      min-spare-threads: 1000

  session:
    jdbc:
      cleanup-cron: "0 0 4 * * *"

  mvc:
    static-path-pattern: /resources/static/**

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    fail-on-missing-locations: true
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
