spring:
  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5432/loja_virtual?autoReconnect=true
    username: postgres
    password: 75128359
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 200
      maximum-pool-size: 550
      idle-timeout: 10000
      pool-name: PoolHikari
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
      temp:
        '[use-jdbc-metadata-defaults]': true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          '[batch_size]': 4
          '[order_inserts]': true
          '[order_updates]': true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    fail-on-missing-locations: true
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b530120f3ce95c
    password: 97477b2a1a77cd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: qSGBPv97fx11LxXSc01SvVP7lgWTZ+1NB1JN5jii4oA=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  server:
    servlet:
      context-path: /loja_virtual
    compression:
      enabled: true
      mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
      min-response-size: 1024
    http2:
      enabled: true
    tomcat:
      max-connections: 50000
      min-spare-threads: 1000

  session:
    jdbc:
      cleanup-cron: "0 0 4 * * *"

  mvc:
    static-path-pattern: /resources/static/**
